/**
 * Internal Ad Copy Generator — Kin-Sell
 *
 * Uses OpenAI Responses API to generate creative ad copy for internal
 * Kin-Sell promotional banners. These are NOT user-submitted ads —
 * they are autonomous internal promotions generated by the platform.
 *
 * Input: category context, trending data, regional signals
 * Output: Ad title, description, CTA text, target page
 *
 * All outputs tagged with source: HYBRID (internal data + AI generation).
 */

import { env } from "../../config/env.js";
import { logger } from "../../shared/logger.js";
import { scoreHybrid, scoreInternal, scoreExternal, type ConfidenceScore } from "../analytics/confidence-score.service.js";

// ── Types ──────────────────────────────────────────────────

export interface GeneratedAdCopy {
  title: string;
  description: string;
  ctaText: string;
  targetPage: string;
  category: string;
  tone: "PROMOTIONAL" | "INFORMATIVE" | "URGENT" | "SEASONAL";
  languageCode: "fr";
}

export interface AdCopyRequest {
  category: string;
  city: string;
  trendDirection?: "GROWING" | "STABLE" | "DECLINING" | "UNKNOWN";
  demandLevel?: "LOW" | "MEDIUM" | "HIGH" | "UNKNOWN";
  listingsCount?: number;
  avgPriceUsdCents?: number;
  seasonalNote?: string;
}

export interface GeneratedAdResult {
  copy: GeneratedAdCopy;
  score: ConfidenceScore;
  generatedAt: string;
}

// ── OpenAI API ─────────────────────────────────────────────

interface OpenAIMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

interface OpenAIResponse {
  output?: Array<{ content?: Array<{ text?: string }> }>;
  choices?: Array<{ message?: { content?: string } }>;
}

async function callOpenAI(messages: OpenAIMessage[]): Promise<{ text: string; success: boolean }> {
  const apiKey = env.OPENAI_API_KEY;
  if (!apiKey) {
    return { text: "", success: false };
  }

  try {
    // Try Responses API first
    const response = await fetch("https://api.openai.com/v1/responses", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        input: messages,
        temperature: 0.7,
        max_output_tokens: 500,
      }),
      signal: AbortSignal.timeout(20_000),
    });

    if (response.ok) {
      const data = (await response.json()) as OpenAIResponse;
      const text = data.output?.[0]?.content?.[0]?.text ?? "";
      if (text) return { text, success: true };
    }

    // Fallback to Chat Completions API
    const chatResponse = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages,
        temperature: 0.7,
        max_tokens: 500,
        response_format: { type: "json_object" },
      }),
      signal: AbortSignal.timeout(20_000),
    });

    if (!chatResponse.ok) {
      logger.warn(`[OpenAI] API error: ${chatResponse.status}`);
      return { text: "", success: false };
    }

    const chatData = (await chatResponse.json()) as OpenAIResponse;
    const chatText = chatData.choices?.[0]?.message?.content ?? "";
    return { text: chatText, success: chatText.length > 10 };
  } catch (err) {
    logger.warn({ err }, "[OpenAI] Request failed");
    return { text: "", success: false };
  }
}

// ── Public API ─────────────────────────────────────────────

/**
 * Generate a single promotional ad copy for an internal Kin-Sell banner.
 */
export async function generateAdCopy(request: AdCopyRequest): Promise<GeneratedAdResult> {
  const { category, city, trendDirection, demandLevel, listingsCount, avgPriceUsdCents, seasonalNote } = request;

  const contextParts: string[] = [
    `Catégorie: ${category}`,
    `Ville: ${city}`,
  ];
  if (trendDirection && trendDirection !== "UNKNOWN") contextParts.push(`Tendance: ${trendDirection}`);
  if (demandLevel && demandLevel !== "UNKNOWN") contextParts.push(`Demande: ${demandLevel}`);
  if (listingsCount) contextParts.push(`${listingsCount} annonces disponibles`);
  if (avgPriceUsdCents) contextParts.push(`Prix moyen: ${(avgPriceUsdCents / 100).toFixed(0)} USD`);
  if (seasonalNote) contextParts.push(`Note saisonnière: ${seasonalNote}`);

  const messages: OpenAIMessage[] = [
    {
      role: "system",
      content: `Tu es le rédacteur publicitaire interne de Kin-Sell, une marketplace basée à Kinshasa, RD Congo.
Tu génères des bannières promotionnelles INTERNES pour mettre en avant des catégories de produits/services sur la plateforme.
Tes textes sont en français, concis, accrocheurs et adaptés au marché congolais.
Tu ne mens jamais sur les prix ou la disponibilité.
Retourne UNIQUEMENT un JSON valide avec cette structure :
{
  "title": "<max 60 caractères, accrocheur>",
  "description": "<max 120 caractères, informatif>",
  "ctaText": "<max 20 caractères, call-to-action>",
  "targetPage": "<explorer|sokin|home>",
  "tone": "<PROMOTIONAL|INFORMATIVE|URGENT|SEASONAL>"
}`,
    },
    {
      role: "user",
      content: `Génère une bannière promotionnelle interne Kin-Sell pour cette situation :\n${contextParts.join("\n")}`,
    },
  ];

  const { text, success } = await callOpenAI(messages);

  // Score: hybrid of internal context data + AI generation
  const internalScore = scoreInternal(listingsCount ?? 0, category);
  const externalScore = scoreExternal(success, 0, "OpenAI GPT-4o-mini");

  if (success) {
    try {
      const parsed = JSON.parse(text);
      return {
        copy: {
          title: String(parsed.title ?? "").slice(0, 60),
          description: String(parsed.description ?? "").slice(0, 120),
          ctaText: String(parsed.ctaText ?? "Découvrir").slice(0, 20),
          targetPage: ["explorer", "sokin", "home"].includes(parsed.targetPage) ? parsed.targetPage : "explorer",
          category,
          tone: ["PROMOTIONAL", "INFORMATIVE", "URGENT", "SEASONAL"].includes(parsed.tone) ? parsed.tone : "PROMOTIONAL",
          languageCode: "fr",
        },
        score: scoreHybrid(internalScore, externalScore),
        generatedAt: new Date().toISOString(),
      };
    } catch { /* fall through */ }
  }

  // Fallback: generate deterministic internal copy
  return {
    copy: buildFallbackCopy(category, city, listingsCount ?? 0),
    score: internalScore,
    generatedAt: new Date().toISOString(),
  };
}

/**
 * Generate multiple ad copies for a batch of categories.
 */
export async function generateBatchAdCopies(
  categories: Array<{ category: string; listingsCount: number; avgPriceUsdCents?: number }>,
  city: string = "Kinshasa",
): Promise<GeneratedAdResult[]> {
  const results: GeneratedAdResult[] = [];
  // Process sequentially to respect rate limits
  for (const cat of categories.slice(0, 6)) {
    const result = await generateAdCopy({
      category: cat.category,
      city,
      listingsCount: cat.listingsCount,
      avgPriceUsdCents: cat.avgPriceUsdCents,
    });
    results.push(result);
  }
  return results;
}

// ── Fallback ───────────────────────────────────────────────

const FALLBACK_TEMPLATES: Array<{ title: (c: string) => string; desc: (c: string, n: number) => string; cta: string; tone: GeneratedAdCopy["tone"] }> = [
  {
    title: (c) => `${c} sur Kin-Sell`,
    desc: (c, n) => n > 0 ? `${n} annonces ${c.toLowerCase()} vous attendent` : `Découvrez nos ${c.toLowerCase()} à Kinshasa`,
    cta: "Explorer",
    tone: "PROMOTIONAL",
  },
  {
    title: (c) => `Trouvez votre ${c.toLowerCase()} idéal`,
    desc: (_c, _n) => `Les meilleurs prix de Kinshasa, négociables en direct`,
    cta: "Voir les offres",
    tone: "INFORMATIVE",
  },
  {
    title: (c) => `${c} — Nouveautés !`,
    desc: (c, _n) => `Nouvelles annonces ${c.toLowerCase()} ajoutées récemment`,
    cta: "Découvrir",
    tone: "PROMOTIONAL",
  },
];

function buildFallbackCopy(category: string, _city: string, listingsCount: number): GeneratedAdCopy {
  const template = FALLBACK_TEMPLATES[Math.floor(Math.random() * FALLBACK_TEMPLATES.length)];
  return {
    title: template.title(category).slice(0, 60),
    description: template.desc(category, listingsCount).slice(0, 120),
    ctaText: template.cta,
    targetPage: "explorer",
    category,
    tone: template.tone,
    languageCode: "fr",
  };
}
